### ISSUE TITLE
Informazioni di emergenza non tradotto

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V8_Italy#100]
<img src="http://oi67.tinypic.com/jhevtk.jpg">

**Comment by ale8530** [comment]
Ma dove hai pescato questa roba?

**Comment by ghost** [comment]
Con l'ottimizzazione MIUI disattivata mi crea l'opzione "Utenti" (interamente tradotta in italiano. Mah...) nelle impostazioni, entra in quel menú e.clicca su "informazioni relative all'emergenza".

**Comment by ale8530** [comment]
mmm ok sarà qualche menu nascosto, comunque non è prioritario perché l'opzione non va disattivata, disattivare quell'opzione crea menu che non devono esistere

**Comment by ghost** [comment]
Creerà anche menù che non devono esistere, però disattivare quell'ordine mi ha portato benefici in termini di RAM :D (e mi sa che la funzionalità app bloccate in background, come ho detto va fixata).

**Comment by ale8530** [comment]
Individuato apk si chiama EmergencyInfo.apk, nei prossimi giorni sarà tradotto
