### ISSUE TITLE
Mancata traduzione

### ISSUE THREAD

**Issue by bugrider87** [MishFdM/MIUI_V8_Italy#101]
segralo mancata traduzione su redmi note 3 special edition su rom miui it 7.2.16 mancata traduzione del informativa inserimento micro sd

[IMG]http://i66.tinypic.com/zxmbus.png[/IMG]

[IMG]http://i67.tinypic.com/ru4j12.png[/IMG]

**Comment by ghost** [comment]
Si, é capitato anche a me, ma dopo aver rimosso la notifica, quando riappariva me la ritrovavo tradotta (non so se la stessa cosa accade anche a te). Sarà un doppio menú...

**Comment by ale8530** [comment]
Farò dei controlli

**Comment by ale8530** [comment]
Ho verificato la stringa "<string name="ext_media_mountable_notification_message">Touch to open in Explorer.</string>" contenuta in MiuiSystemUi.apk è tradotta, quindi probabilmente è solo un problema di primo avvio, nelle rom non ci sono altre stringhe con questa traduzione
