### ISSUE TITLE
Errore di traduzione in Temi>Commenti - Redmi Note 3 Pro (kenzo) - MIUI 6.7.21

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V8_Italy#11]
"Aggiungi ai commenti" andrebbe sostituito con "Aggiungi commento"

Positivo e Negativo andrebbero sostituiti col plurale

<img width="540" alt="screenshot_2016-07-31-05-24-26-542_com android thememanager 1" src="https://cloud.githubusercontent.com/assets/16007271/17274416/fcda7864-56df-11e6-8115-8d2992976bad.png">

**Comment by ale8530** [comment]
Dopo la release 6.7.28
