### ISSUE TITLE
Barra di ricerca e blocco schermo in inglese 

### ISSUE THREAD

**Issue by Federic095** [MishFdM/MIUI_V8_Italy#110]
Sulla ultima Xiaomi.eu per il Kate la scritta sulla barra di ricerca è in inglese. È sempre stata in italiano prima... 
![screenshot_2017-02-26-11-45-17-007_com android settings](https://cloud.githubusercontent.com/assets/22075569/23339006/2a88ea28-fc19-11e6-9756-795024aa98e6.png)
![screenshot_2017-02-26-11-44-59-235_com android chrome](https://cloud.githubusercontent.com/assets/22075569/23339008/3462edc8-fc19-11e6-9152-749041273b93.png)

**Comment by Federic095** [comment]
Ho notato anche che nel blocco schermo c'è un'altra scritta in inglese
![img_20170226_120734](https://cloud.githubusercontent.com/assets/22075569/23339158/58b04ac4-fc1c-11e6-8a5c-f62541adc983.jpg)

**Comment by clavecin87** [comment]
Confermo sul mio mi 5s i problemi di traduzione riportati sopra, e aggiungo anche il seguente, sempre nella schermata di sblocco, quando si tenta di sbloccare con l'impronta:
![screenshot_2017-02-12-23-45-55-636_lockscreen](https://cloud.githubusercontent.com/assets/26075124/23386623/c3df772a-fd57-11e6-8317-d936b061bc85.png)
![screenshot_2017-02-28-01-47-51-871_com android settings](https://cloud.githubusercontent.com/assets/26075124/23386656/fc3446e6-fd57-11e6-8513-5af6ca97f924.png)
