### ISSUE TITLE
Traduzione info impostazioni

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V8_Italy#117]
https://github.com/MishFdM/MIUI_V8_Italy/compare/master...Orlaff:patch-2

**Comment by ale8530** [comment]
Utilizza il servizio PR.

Chiusa

**Comment by ale8530** [comment]
Orlaff fai il fork della nostra repo,poi effettui le modifiche e alla fine fai Pull Request con questo sistema iniettiamo direttamente le tue modifiche se che dobbiamo metterci mano.

PS ovviamente le modifiche saranno verificate.

Ci dai una maggiore mano così :)
