### ISSUE TITLE
Errore di traduzione in Temi>My account - Redmi Note 3 Pro (kenzo) - MIUI 6.7.21

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V8_Italy#12]
"Sfondo" e "Suoneria" andrebbero sostituiti col plurale

<img width="540" alt="screenshot_2016-07-31-05-35-44-541_com android thememanager" src="https://cloud.githubusercontent.com/assets/16007271/17274437/45bef8d8-56e1-11e6-98ef-b376fcde9fa6.png">

**Comment by ale8530** [comment]
Dopo la release 6.7.28
