### ISSUE TITLE
Errore di traduzione in Temi - Redmi Note 3 Pro (kenzo) - MIUI 6.7.21

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V8_Italy#13]
"Sfondo" andrebbe sostituito col plurale

![screenshot_2016-07-31-05-49-00-193_com android thememanager 1](https://cloud.githubusercontent.com/assets/16007271/17274472/c9fa4214-56e2-11e6-8cc9-798f5a880d49.png)

**Comment by ale8530** [comment]
Disponibile dopo la release 6.7.28
