### ISSUE TITLE
Errore di traduzione in Impostazioni>SIM e reti mobili - Redmi Note 3 Pro (kenzo) - MIUI 6.7.21

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V8_Italy#14]
Il titolo del menù è diverso da quello del sottomenù mentre in inglese e cinese sono uguali:

"SIM e reti mobili" e "SIM e dati mobili"

"Componi" andrebbe sostituito con "Chiamate"

![screenshot_2016-07-31-06-01-56-582_com android settings 1](https://cloud.githubusercontent.com/assets/16007271/17274502/8254d832-56e4-11e6-9ddb-3125bbf57a5d.png)

![screenshot_2016-07-31-05-56-08-421_com android phone 1](https://cloud.githubusercontent.com/assets/16007271/17274492/ec9d5c74-56e3-11e6-9d67-524d4574c449.png)

**Comment by ale8530** [comment]
Le sistemazioni saranno disponibili dopo la release 6.7.28
