### ISSUE TITLE
Errore di traduzione in File Explorer>Spazio di archiviazione - Redmi Note 3 Pro (kenzo) - MIUI 6.7.21

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V8_Italy#15]
Mancano i due punti e lo spazio in relazione alle diverse categorie

![screenshot_2016-07-31-06-19-17-798_com android fileexplorer 1](https://cloud.githubusercontent.com/assets/16007271/17274550/18fa84ec-56e7-11e6-96a9-e3bc742fb75d.png)
![screenshot_2016-07-31-06-18-26-712_com android fileexplorer 1](https://cloud.githubusercontent.com/assets/16007271/17274553/2e1188b2-56e7-11e6-8f83-9131530cf599.png)

**Comment by ale8530** [comment]
6.7.28 è già fissato
