### ISSUE TITLE
Alcune parti di sistema non tradotte

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V8_Italy#153]
@MishFdM 

Ho trovato alcune stringhe non tradotte, ma mancanti nella vostra repo. Postresti aggiungerle? Grazie.

<img src="http://oi64.tinypic.com/4vmfeg.jpg">
<img src="http://oi64.tinypic.com/2jo2d.jpg">
<img src="http://oi66.tinypic.com/sc8kjp.jpg">
<img src="http://oi65.tinypic.com/xyept.jpg">
<img src="http://oi67.tinypic.com/15dktmp.jpg">
<img src="http://oi63.tinypic.com/2q1yq8p.jpg">
<img src="http://oi64.tinypic.com/11rggty.jpg">

**Comment by ale8530** [comment]
Che dispositivo hai qui devo vedere bene, va sempre indicato il terminale e release

**Comment by ale8530** [comment]
Errore non doveva essere chiusa

**Comment by ghost** [comment]
Tutto te hai fatto xD.

Comunque Mi Max con ultima 7.3.23 eu.

**Comment by ale8530** [comment]
Mi sono sbagliato :D

**Comment by ghost** [comment]
Rimangono solo 3 bug da fixare. :D

**Comment by ghost** [comment]
Settimo, sesto e secondo screen.

**Comment by ale8530** [comment]
Devo fare una ricerca approfondita non è semplice :)

**Comment by ghost** [comment]
Guarda ti do un suggerimento su quello del secondo screen.

Ricordi quando mi chiudesti quel famoso PR di un paio di giorni fà, perchè non potevo aggiungere stringhe? Eh...con quello puoi risolvere il problema. Fallo vedere a @MishFdM nel caso.

Intanto cerco di capire se riesco a trovare gli altri due.

**Comment by ale8530** [comment]
Domani vedo le stringhe inserite ma preferisco metterle io vedendo i tuoi suggerimenti

**Comment by ghost** [comment]
@ale8530

Ed é giusto così. Io mi rifaccio alla repo spagnola che aggiornano prima del rilascio settimanale (mi sa che qualcuno di loro é entrato nel programma alpha, che rilascia le rom il lunedì/martedì), ma non é detto che i miei fix in questo senso siano corretti. :)

**Comment by ale8530** [comment]
Come vedi non era una passeggiata issue chiusa :)

**Comment by ghost** [comment]
Ne ho mai detto che lo fosse. :)

Grazie comunque. :D
