### ISSUE TITLE
Errore di traduzione in Temi - Redmi Note 3 Pro (kenzo) - MIUI 6.7.21

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V8_Italy#16]
Quando si elimina un tema dai preferiti appare scritto "Rimuovi dai preferiti" invece di "Rimosso dai preferiti"

![screenshot_2016-07-31-08-07-41-308_com android thememanager](https://cloud.githubusercontent.com/assets/16007271/17274917/53ba6c64-56f6-11e6-9100-a7d493a77e3b.png)

**Comment by ale8530** [comment]
Credo sia già stato sistemato sulla release 6.7.28 che rilasceremo in questi giorni.

Ho comunque aggiustato un'altra sezione della rom ;)
