### ISSUE TITLE
Prima le aggiungete e poi le levate

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V8_Italy#167]
@MishFdm @ale8530 

Queste erano stringhe di traduzione della modalità sviluppatore.

<img src="http://oi65.tinypic.com/2qas7pw.jpg">

**Comment by ale8530** [comment]
é le troppe versioni android che stanno creando il problema, vediamo di sistemarle per evitare la perdita delle stringhe

**Comment by ghost** [comment]
Pure queste hai aggiunto te, e sono state tolte (i famosi bug che segnalai)

<img src="http://oi64.tinypic.com/241qcma.jpg">

**Comment by ghost** [comment]
<img src="http://oi68.tinypic.com/33lyvky.jpg">

**Comment by ale8530** [comment]
Le ultime con ANR non le trovo su gemini, se gentilmente puoi fare PR mettendole su

device/gemini/Settings.apk/values-it-rIT/strings.xml

**Comment by ghost** [comment]
Fatto, e queste sono altre stringhe aggiunte ultimamente e non tradotte

<img src="http://oi65.tinypic.com/1yyqg.jpg">
<img src="http://oi65.tinypic.com/1yyqg.jpg">
<img src="http://oi64.tinypic.com/20sgeht.jpg">

**Comment by ale8530** [comment]
Saranno tradotte da Mish quando può

**Comment by ale8530** [comment]
Chiusa https://github.com/MishFdM/MIUI_V8_Italy/commit/eb89655c3276d63ae262f1b8cbf18abefcb670af
