### ISSUE TITLE
Errore di traduzione nella barra delle notifiche - Note 3 Pro (kenzo) - MIUI 6.7.21

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V8_Italy#17]
Nel pannello delle notifiche aooaew scritto "Soleggiati" invece di "Soleggiato"

![screenshot_2016-08-01-21-29-28-180_com teslacoilsw launcher-1](https://cloud.githubusercontent.com/assets/16007271/17306425/464593fc-5830-11e6-8878-7344e9b47c37.png)

**Comment by ale8530** [comment]
Bug traduzione server meteo non dipende da noi.

Chiusa
