### ISSUE TITLE
Errore Traduzione Lockscreen

### ISSUE THREAD

**Issue by ricklionheart** [MishFdM/MIUI_V8_Italy#171]
Salve a tutti, 
vorrei segnalare questo piccolo errore di traduzione che ho riscontrato sul Mi5 7.4.6 

![screenshot](https://cloud.githubusercontent.com/assets/27385360/24983714/4ff7d87a-1fe9-11e7-8f60-0909b6882741.png)

Grazie

**Comment by ale8530** [comment]
Non ci sono bug

**Comment by ricklionheart** [comment]
Non dovrebbe essere tradotta anche la parte che ho sottolineato?

**Comment by ale8530** [comment]
e' già tradotto , appena verificato

**Comment by ricklionheart** [comment]
A me continua a mostrarmelo ancora anche con la 7.4.14

Si verifica quando (da dispositivo bloccato chiaramente) :
- Scorri in alto per attivare il tastierino numerico
- Metti un dito non registrato per 3 volte consecutive (tutte e 3 errate quindi)
- Ti appare la schermata che ho mostrato io
- Se provi altre 2 volte appare in la voce corretta in italiano "Impossibile leggere le impronte digitali .." dopo ti obbliga per sbloccare il dispositivo ad inserire il pin o la password.

Non è un problema gravissimo anzi, però mi piacerebbe renderlo noto

**Comment by ale8530** [comment]
La xiaomi.eu è più indietro, la miui.it è ok, abbiamo committato 30 minuti fa delle stringhe ed è stato risolto.

Non ce bisogno di polemizzare, se continua nella prossima release xiaomi.eu provvederò a sistemare, ma ora questo bug non c'è

**Comment by ricklionheart** [comment]
Non era mia intenzione nè polemizzare nè creare problemi, grazie per la segnalazione. Auguro una buona serata

**Comment by ale8530** [comment]
Se nella prossima release hai ancora il bug scrivi qui che provvederò a fare una ricerca approfondita :)
