### ISSUE TITLE
Traduzioni varie 

### ISSUE THREAD

**Issue by Federic095** [MishFdM/MIUI_V8_Italy#172]
Segnalo traduzioni mancanti nell'ultima stable per Kate 
![screenshot_2017-04-25-20-39-06-464_com android settings](https://cloud.githubusercontent.com/assets/22075569/25401973/a4f7cd54-29f7-11e7-87a3-ec42d7df504c.png)
![screenshot_2017-04-25-20-40-04-063_com android settings](https://cloud.githubusercontent.com/assets/22075569/25401982/aa412a58-29f7-11e7-82a0-ec23851202f9.png)
![screenshot_2017-04-25-20-38-52-340_com android deskclock](https://cloud.githubusercontent.com/assets/22075569/25401984/ae319800-29f7-11e7-8a6a-7fe4c1eeddff.png)

**Comment by ale8530** [comment]
Segnalare a xiaomi.eu decidono loro come implementare la nostra traduzione

**Comment by ale8530** [comment]
Ho dimenticato perché si tratta di stabile
