### ISSUE TITLE
errore traduzione redmi note 3 special edition

### ISSUE THREAD

**Issue by bugrider87** [MishFdM/MIUI_V8_Italy#174]
salve ho notato un piccolissimo errore di traduzione nella notifica ultima sincronizzazione vi e un %s che dovrebbe indicare il numero in giorni mi pare allego screanshot <a href="http://it.tinypic.com?ref=30jtvle" target="_blank"><img src="http://i67.tinypic.com/30jtvle.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by MishFdM** [comment]
Fixed
