### ISSUE TITLE
Errore traduzione

### ISSUE THREAD

**Issue by Vladi69** [MishFdM/MIUI_V8_Italy#175]
Versione installata: 7.5.11 by xiaomi.eu
Dispositivo: Redmi 4 Pro
Percorso: schermata di lock screen durante la carica della batteria
Frase contenente il bug: Dang sac pin (vietnamita)
Suggerimento traduzione: Batteria in carica

Errore già presenta nella versione precedente

![screenshot_2017-05-12-23-38-08-275_lockscreen1](https://cloud.githubusercontent.com/assets/28661149/26023279/d478c492-37b8-11e7-80d3-48cbf5bf3398.png)

**Comment by ale8530** [comment]
È un problema del tuo tema.

Chiusa
