### ISSUE TITLE
Errore di traduzione in Sicurezza>Permessi - Redmi Note 3 Pro (kenzo) - MIUI 6.7.21

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V8_Italy#18]
"Installa tramite UUSB"

![screenshot_2016-08-03-06-18-34-731_com miui securitycenter](https://cloud.githubusercontent.com/assets/16007271/17353710/9c51d996-5942-11e6-9054-dc9e61cb64b3.png)

**Comment by ale8530** [comment]
Aggiorna la rom bug inestistente!
