### ISSUE TITLE
Traduzione dati mobili

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V8_Italy#182]
<img src="http://oi67.tinypic.com/zv8t2u.jpg">

**Comment by ale8530** [comment]
Additional setting è stato fissato nel nostro commit di aggiornamento stringhe non presente in xiaomi.eu

**Comment by Orlaff** [comment]
@ale8530

Ho installato la vostra rom 7.5.11 e questa parte non é tradotta.

**Comment by ale8530** [comment]
Credo che io parlo italiano-->Additional setting è stato fissato nel nostro commit di aggiornamento **stringhe non presenti in xiaomi.eu**

**Comment by Orlaff** [comment]
Ah ok...No perché essendo che ho segnalato il bug nello stesso momento di altri (che invece sono presenti in questa release), mi é sorto il dubbio.

**Comment by ale8530** [comment]
Il dubbio non deve sorgere,se ti dico fissato è fissato, poi è ovvio che il rilascio è quasi sempre successivo anche alla nostra release . 

A dimostrazione che non ti fidi ti faccio screenshot (è una rom interna non pubblica)

![screenshot_2017-05-16-17-01-07-162_com miui securitycenter](https://cloud.githubusercontent.com/assets/6189615/26113002/9ed7170a-3a59-11e7-807d-9c643964bbdc.png)

Non è il massimo mettere in dubbio il nostro lavoro.

Il fatto che non è presente perché spesso le rom sono elaborate prima di alcuni fix.
la regola fondamentale:

**# ASPETTARE UNA RELEASE SUCCESSIVA PRIMA DI VENIRE A COMMENTARE UN BUG CHIUSO!**

**Comment by Orlaff** [comment]
@ale8530

Non giudico il lavoro di nessuno, questa situazione si é creata perche in passato é capitata una cosa simile (non ricorderai, ma non fa nulla).

Aldilà di questo non sono il tipo che si ferma su sto tipo di argomenti (e lo sai bene dopo tutto quello che ho fatto), perciò direi fine...Non é il caso di fissarsi.
