### ISSUE TITLE
Traduzione area test

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V8_Italy#186]
<img src="http://oi66.tinypic.com/xdxuhf.jpg">

**Comment by ale8530** [comment]
Attivi questo menu facendo 7 volte tap su kernel?

Ti chiedo la cortesia di verificare sull'app galleria, premendo su questo screenshot,altro, dettagli se mi vedi dove sta scritto percorso come si chiama l'app com.ecc...

**Comment by ghost** [comment]
Tap 3 volte su Kernel.

Comunque l'app si chiama: con.miui.cit

**Comment by ale8530** [comment]
Ottimo cosi riduco il campo di ricerca

**Comment by ale8530** [comment]
Prossima release ci sarà il fix
