### ISSUE TITLE
Traduzione Cit

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V8_Italy#188]
<img src="https://s14.postimg.org/95w86gy41/IMG_20170526_150613.jpg">
<img src="https://s9.postimg.org/w710yr2yn/Screenshot_2017-05-26-15-05-12-218_com.miui.cit.png">

**Comment by ale8530** [comment]
Inserite qui abb8a4d1ad01d6e32f7f49c2393ea743d47e9869

Saranno presenti su l'attuale miui.it
