### ISSUE TITLE
Traduzione Lockscreen

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V8_Italy#190]
Fuori visione

<img src="https://preview.ibb.co/nHdUAv/IMG_20170605_172322.jpg">

**Comment by Orlaff** [comment]
@ale8530

Vedi se riesci ad aggiungere uno spazio vicino ad "ore". Così è più pulito...

**Comment by ale8530** [comment]
Lo hai fissato tu-->https://github.com/MishFdM/MIUI_V8_Italy/commit/5458daa430923ed3c382050e0a6d53da9a05e397 

Ottimo lavoro
