### ISSUE TITLE
Traduzione foto

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V8_Italy#198]
<img src="https://preview.ibb.co/mR4NOQ/Screenshot_2017_06_16_14_08_37_019_com_miui_gallery.png">

Today...

**Comment by ghost** [comment]
In più c'è un altro bug durante il caricamento della home, che sull'ultima 7.6.15 fa apparire un altro messaggio al posto di "caricamento launcher".

Purtroppo non posso fare screen, perche sono le fasi iniziali dopo lo sblocco.

**Comment by ale8530** [comment]
Sul fatto della home puoi fornire screenshot o frase? :)

**Comment by ale8530** [comment]
Ah letto su screenshot,mi basta la frase in inglese

**Comment by ghost** [comment]
@ale8530

La frase è "Just a sec...". Si legge dopo quella "Caricamento launcher..."

**Comment by ghost** [comment]
Per il resto quella dello screen è "Today".

**Comment by MishFdM** [comment]
Dovrebbe essere tutto OK per MIUI ITA 7.6.15, verificare.

**Comment by ghost** [comment]
@MishFdM

Si ho notato che sono state aggiunte sia le stringe "oggi" e "ieri" e sia quella "solo un attimo..."

**Comment by ale8530** [comment]
Chiusa nel caso Orlaff commenterà questa issue
