### ISSUE TITLE
Bug in Impostazioni>Impostazioni aggiuntive >Locale - Redmi Note 3 Pro (kenzo) - MIUI 6.7.28

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V8_Italy#20]
In Impostazioni - Impostazioni aggiuntive - Locale manca l'Italia. Se invece si imposta la lingua inglese, l'Italia compare tra i Paesi selezionabili.

Locale potrebbe essere sostituito con Paese

![screenshot_2016-08-05-04-52-07-873_com android settings](https://cloud.githubusercontent.com/assets/16007271/17424923/af427d76-5ac8-11e6-8f88-288ebc5b88c3.png)

![screenshot_2016-08-05-04-58-31-559_com android settings](https://cloud.githubusercontent.com/assets/16007271/17425070/b4b35720-5ac9-11e6-8daa-01ab5152f474.png)

![screenshot_2016-08-05-05-02-10-026_com android settings](https://cloud.githubusercontent.com/assets/16007271/17425081/d239a57e-5ac9-11e6-8db9-9076db7da282.png)

**Comment by ale8530** [comment]
Chiusa la rom miui.it ha disattivato questo menu, ti chiedo la gentilezza di utilizzare le nostre rom al massimo xiaomi.eu altrimenti non postare bug inesistenti
