### ISSUE TITLE
Traduzione sicurezza

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V8_Italy#201]
Hanno raggiunto il game booster, ma il titolo e la descrizione non corrispondono.

<img src="https://preview.ibb.co/e22iXk/Screenshot_2017_06_18_11_42_19_481_com_miui_securitycenter.png">

**Comment by MishFdM** [comment]
Tradotto ma attenzione: le stringhe tradotte fanno riferimento effettivamente all' Assistente busta rossa. Da verificare se di fatto nella schermata si accede a Game Booster. In caso contrario riaprire la issue.

**Comment by ghost** [comment]
@MishFdM

Per il momento si (reupload ROM del 17). Se cambieranno di nuovo non so...
