### ISSUE TITLE
Traduzione foto

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V8_Italy#208]
<img src="https://preview.ibb.co/khrjTQ/Screenshot_2017_06_24_00_49_34_612_com_android_camera.png">
<img src="https://preview.ibb.co/kuG7hk/Screenshot_2017_06_24_00_49_50_358_com_android_camera.png">

**Comment by ghost** [comment]
Age & gender

Pocket mode (più descrizione)

**Comment by ale8530** [comment]
ange & gender già fissato
