### ISSUE TITLE
Traduzione MiCloud

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V8_Italy#209]
<img src="https://preview.ibb.co/mdR7hk/IMG_20170624_013255.jpg">

**Comment by ghost** [comment]
"Personal info" e traduzione degli elementi presenti sul cloud personale (notare "firstlevel").

**Comment by ale8530** [comment]
Chiusa non si può tradurre

**Comment by ale8530** [comment]
firstlevel non traducibile

**Comment by ale8530** [comment]
Già fissata
