### ISSUE TITLE
App Sicurezza

### ISSUE THREAD

**Issue by birimbo79** [MishFdM/MIUI_V8_Italy#22]
La nuova app Sicurezza necessita di essere tradotta:
![screenshot_2016-08-13-10-22-54-877_com miui securitycenter](https://cloud.githubusercontent.com/assets/20362846/17642319/c787ebe0-6140-11e6-9811-d712274faffa.png)
![screenshot_2016-08-13-10-23-01-093_com miui securitycenter](https://cloud.githubusercontent.com/assets/20362846/17642320/cbc10ca0-6140-11e6-9882-1e3a18cfd8e9.png)
Nelle impostazioni di chiamata accanto la voce Blacklist viene indicato "Registrazione automatica attiva" come nella voce relativa al registratore chiamate. Sarebbe più corretto tradurre con "Filtro chiamate attivo/disattivo" per evitare di confonderlo con il registratore chiamate.
![screenshot_2016-08-13-10-27-44-186_com android phone](https://cloud.githubusercontent.com/assets/20362846/17642325/05350afe-6141-11e6-84c8-69372121534e.png)
Grazie per l'ottimo lavoro che fate :)

**Comment by ale8530** [comment]
Sia blacklist e impostazioni di registrazione utilizzano la stessa stringa di traduzione, ho utilizzato la voce generica "Attivato" e "Disattivato" per uniformare il menu
