### ISSUE TITLE
Traduzione ricerca impostazioni

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V8_Italy#221]
<img src="https://preview.ibb.co/n9sRck/IMG_20170627_162003.jpg">

**Comment by ale8530** [comment]
Or-laf se vuoi dare una mano con la traduzione v.9 trovi tutto [qui ](https://github.com/MishFdM/MIUI_V9_Italy/commits/master)

**Comment by ghost** [comment]
Ottimo, ora mi salvo il link

**Comment by ale8530** [comment]
Ci sono molte stringhe da tradurre se vuoi, utilizza il solito sistema delle PR :)

**Comment by ghost** [comment]
Le parti piú ricolme di stringhe quali sono?

**Comment by ale8530** [comment]
Settings.apk, Contacts.apk,cmq un pò di tutto xke ce molta traduzione nuova
