### ISSUE TITLE
Traduzione Antivirus

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V8_Italy#223]
<img src="https://preview.ibb.co/m3iMCk/IMG_20170629_182036.jpg">
<img src="https://preview.ibb.co/hQ3A55/IMG_20170629_182024.jpg">
<img src="https://preview.ibb.co/eZBqq5/IMG_20170630_152744.jpg">

**Comment by ale8530** [comment]
Già tradotto, per evitare perdite di tempo,aspettare almeno due release xiaomi.eu prima di segnalare.

**Comment by ghost** [comment]
Annoteró...
