### ISSUE TITLE
Crash app Impostazioni

### ISSUE THREAD

**Issue by stefMI** [MishFdM/MIUI_V8_Italy#229]
Salve, ho un problema su una stabile Eu (8.5.3.0) per il Redmi Note 4 Snapdragon (mido). In pratica quando vado nelle impostazioni di sviluppatore, l'app impostazioni crasha per arresto anomalo.
Ho notato però che se metto la lingua inglese sul telefono questo crash non succede, presumo dunque che il problema è con la lingua italiana.

Spero che il problema venga risolto subito. 
Vi ringrazio, Stefano

**Comment by ale8530** [comment]
Mi spiace ma seguiamo solo la linea developer la stabile non la seguiamo,non so quale traduzione è stata inserita in quella stabile mi spiace

**Comment by stefMI** [comment]
Va bene, ti ringrazio lo stesso:)
