### ISSUE TITLE
browser home

### ISSUE THREAD

**Issue by nicoloserafino** [MishFdM/MIUI_V8_Italy#23]
Nella home del browser visualizzo la frase "sii sempre convinto che qualcosa di meraviglioso" (peraltro incompleta) invece che quella indicata nella repo "pensa sempre che qualcosa di stupendo stia per accadere". Perchè?

ROM xiaomi.eu weekly 6.8.11

![screen](https://cloud.githubusercontent.com/assets/13679287/17734794/bc413372-647e-11e6-8a3a-f0c8dc207169.png)

**Comment by MishFdM** [comment]
Questa non è una stringa della nostra traduzione, presente nelle global (comunque abbiamo allineato alla nostra traduzione)

**Comment by nicoloserafino** [comment]
Infatti non riesco a spiegarmi quale traduzione sia presente. La vostra repo è anche linkata sotto il link alla mia ROM su xiaomi.eu e ho visto che è corretta. Che sia un errore solo di questa settimana? Attenderò giovedì per scoprirlo :)

**Comment by MishFdM** [comment]
Esistono due linee di traduzione, Miui.it (utilizzata anche da Xiaomi.eu) e quella ufficiale Xiaomi (utilizzata per le ROM ufficiali Global developer). Noi gestiamo la nostra Miui.it ma supervisioniamo anche quella di Xiaomi, che resta spesso incompleta e non aggiornata. La cosa strana è che ti ritrovi la traduzione global avendo flashato una ROM Xiaomi.eu.

**Comment by nicoloserafino** [comment]
Con la weekly di oggi è tornata, correttamente, la vostra traduzione anche nella home del browser. Grazie per il supporto!
