### ISSUE TITLE
disattivazione WIFI

### ISSUE THREAD

**Issue by carletto75** [MishFdM/MIUI_V8_Italy#230]
Da quando ho installato l'ultima versione della miui.it, il miPad2 tende a disattivare il WIFI.
Anche riattivandolo manualmente, viene spento forzatamente.
Forse succede maggiormente attivando l'impostazione Ottimizzazioni MIUI, ma non ne sono sicuro.

**Comment by ale8530** [comment]
E' un bug rom non dipende da noi
