### ISSUE TITLE
errore su mi mix con versione miui it 9.1.2.0 stabile 

### ISSUE THREAD

**Issue by caio66** [MishFdM/MIUI_V8_Italy#231]
![screenshot_2017-11-25-11-43-49-878_com miui home](https://user-images.githubusercontent.com/33977977/33230155-9b7b8222-d1de-11e7-8f5d-7ad0d31b04cb.png)

**Comment by caio66** [comment]
Buongiorno, dopo aver installato la versione stabile ogni tanto mi esce questo errore

**Comment by ale8530** [comment]
Non dipende dalla traduzione e cmq è v9 non v8.

Chiusa
