### ISSUE TITLE
Risparmio batteria

### ISSUE THREAD

**Issue by Flavio94** [MishFdM/MIUI_V8_Italy#3]
![screenshot_2016-07-08-17-16-25-731_com miui securitycenter](https://cloud.githubusercontent.com/assets/20358680/16692792/b15f34a6-4532-11e6-9e7f-2384d4e0516a.png)
![screenshot_2016-07-08-17-16-34-185_com miui securitycenter](https://cloud.githubusercontent.com/assets/20358680/16692817/c7c4ee84-4532-11e6-9869-3f7576306efd.png)
Per favore sistemate la traduzione, lo farei io ma non so come si fa! 
Grazie!

**Comment by MishFdM** [comment]
Corretto, grazie per la segnalazione.
