### ISSUE TITLE
Simbolo > in informazioni meteo

### ISSUE THREAD

**Issue by kadariuk** [MishFdM/MIUI_V8_Italy#32]
![screenshot_2016-08-24-18-34-46-048_com miui home](https://cloud.githubusercontent.com/assets/4078432/17940274/a5843818-6a2e-11e6-8601-33fb5b804e1c.png)

**Comment by rgreco87** [comment]
Ciao, posso chiederti il dispositivo che utilizzi e la versione della ROM installata?

Ricordati sempre di indicare queste informazioni, grazie!

**Comment by kadariuk** [comment]
Ciao si scusami hai ragione dispositivo mi5, versione 6.8.18 ma il problema
è presente anche nelle precedenti versioni di miui 8 settimanali.

Il 25 ago 2016 1:23 AM, "Roberto" notifications@github.com ha scritto:

Ciao, posso chiederti il dispositivo che utilizzi e la versione della ROM
installata?

Ricordati sempre di indicare queste informazioni, grazie!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/MishFdM/MIUI_V8_Italy/issues/32#issuecomment-242238650,
or mute the thread

**Comment by rgreco87** [comment]
Quel simbolo non fa parte delle stringhe di traduzione, è probabile che sia altrove. @MishFdM

**Comment by rgreco87** [comment]
Se ci fai caso, in questo video ufficiale sulla MIUI 8 si vede che è proprio così: https://youtu.be/7gukMzAQBSk?t=48s

**Comment by kadariuk** [comment]
Ho visto il video ma comunque in inglese non trovo quel simbolo.
Non é possibile che nell'xml ci sia un riferimento sbagliato alla relativa
codifica ASCII del simbolo > &gt mi sembra?

Il 25 ago 2016 1:45 AM, "Roberto" notifications@github.com ha scritto:

**Comment by ale8530** [comment]
Chiusa
