### ISSUE TITLE
Bugs in traslation - English ----> Italiano

### ISSUE THREAD

**Issue by birimbo79** [MishFdM/MIUI_V8_Italy#4]
Hi! I found these errors in translation:
![screenshot_2016-07-08-23-25-45-048_com android settings 1](https://cloud.githubusercontent.com/assets/20362846/16702365/c711a8c8-4565-11e6-8e72-b698a1a2b1d0.png)
"Lock screen shortcuts" ----> "Scorciatoie schermata di blocco"
"Set shortcuts for 2 apps on the Lock screen" ----> "Seleziona le scorciatoie per 2 app sulla schermata di blocco"

![screenshot_2016-07-08-23-25-50-882_com android settings 1](https://cloud.githubusercontent.com/assets/20362846/16702442/3878e710-4566-11e6-9c0a-33ed0f552cf9.jpg)
"Left" ----> "Sinistra"
"Right" -----> "Destra"

![screenshot_2016-07-08-23-26-12-387_com miui securitycore 1](https://cloud.githubusercontent.com/assets/20362846/16702462/6e5315c2-4566-11e6-8c6a-a8ad9333450e.jpg)
"Create a second space on your phone. Using second space is like having two devices." -----> "Crea una seconda partizione nel tuo telefono. Usando Second Space sarà come avere due telefoni."

![screenshot_2016-07-08-23-29-28-372_com miui home 1](https://cloud.githubusercontent.com/assets/20362846/16702495/b25ec842-4566-11e6-9782-61d1a469f6d1.jpg)
The icon for "Google" app is wrong (microphone) while the original is a "G" 
![unnamed](https://cloud.githubusercontent.com/assets/20362846/16702539/19e48650-4567-11e6-96d0-7e8c96a8bd90.png)

Please fix it and thank you for your job :)

**Comment by ale8530** [comment]
Fissato solo parte dei collegamenti.

**Comment by birimbo79** [comment]
Redmi 3 Pro - versione 6.7.14
**Scorciatoie schermata di blocco**
![screenshot_2016-07-08-23-25-45-048_com android settings](https://cloud.githubusercontent.com/assets/20362846/16895992/aca01c00-4b86-11e6-8778-f79cca9ec0b0.png)
**Formato della data**
![screenshot_2016-07-16-10-20-46-603_com android settings](https://cloud.githubusercontent.com/assets/20362846/16895995/d882177e-4b86-11e6-9a50-87cc6910fcb2.png)

**Impostazioni chiamate>Elenco Bloccati e Avanzate**
![screenshot_2016-07-16-15-34-20-888_com android phone](https://cloud.githubusercontent.com/assets/20362846/16896034/c5fc5410-4b87-11e6-91d8-0f520bb207e5.png)

**Batteria in carica**
![screenshot_2016-07-16-15-54-07-346_com miui home](https://cloud.githubusercontent.com/assets/20362846/16896038/e377260a-4b87-11e6-946b-5da3a599e334.png)

Inoltre ci sono poi le scritte all'interno delle app Second Space e Clone app che non so se sia possibile tradurre e l'icona di Google che non so se sia possibile ripristinare in "G". Grazie :)
