### ISSUE TITLE
Applicazione Temi

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V8_Italy#44]
Da tradurre:

Top charts
Categories
Wallpapers
Downloaded
Featured

**Comment by ghost** [comment]
Versione 6.9.15

**Comment by ingbrzy** [comment]
not translatable.. its from server side..

**Comment by ale8530** [comment]
Non si fanno cosi le segnalazioni.

Chiusa

Translation:
They do not do so reports

Closed!
