### ISSUE TITLE
Font orologio e batteria nella status bar

### ISSUE THREAD

**Issue by fratoff91** [MishFdM/MIUI_V8_Italy#46]
Salve. Ho notato che nella rom che monto, la xiaomi eu stabile, i font dell'orologio e della batteria sono diversi nella lingua italiana da tutte le altre lingue nonchè da tutte le altre rom che ho provato (global dev, global stabile e anche la vostra miui it). 
Ecco 2 screenshot di esempio:
- INGLESE:
  ![img_20161003_183228](https://cloud.githubusercontent.com/assets/22610054/19065026/6ca5769e-8a11-11e6-9f09-016f6e43facf.jpg)
- ITALIANO:
  ![img_20161003_183254](https://cloud.githubusercontent.com/assets/22610054/19065048/81ad2870-8a11-11e6-9f21-e826ceaf9ae4.jpg)

Mi chiedevo se era possibile fare il cambio del font dato che quello in inglese (e anche presente nella vostra rom di miui it) in grassetto è molto più leggibile e in linea con il resto della rom.
Grazie mille!

UPDATE: non ho scritto il device perchè l'ho notato sempre con tutti i miei device, reedmi 1s, redmi 3 e l'attuale redmi note 3 pro.

**Comment by ale8530** [comment]
La miui.it non ha questo bug devi scrivere a loro

**Comment by fratoff91** [comment]
non è un bug, ma una richiesta. La cosa capita solo con la lingua italiana perciò credo che in qualche modo c'entri...

**Comment by ale8530** [comment]
![screenshot_2016-10-04-10-35-08-832_com android settings](https://cloud.githubusercontent.com/assets/6189615/19068044/260f3426-8a21-11e6-897e-fea88db9e473.png)

Noi mettiamo mano solo a rom miui.it e non ha bug, bisogna chiedere a xiaomi.eu di fare questa modifica, noi a parte la traduzione non mettiamo bocca su queste cose

**Comment by ingbrzy** [comment]
really?
https://github.com/MishFdM/MIUI_V8_Italy/blob/master/Italian/main/MiuiSystemUI.apk/res/values-it/styles.xml

**Comment by fratoff91** [comment]
Ciò, loro mi hanno detto di scrivere qui, lo so che la rom miui it non ha questa cosa... provo a richiedere nel forum di xiaomi eu, allora.

**Comment by ale8530** [comment]
Stiamo vedendo un attimo la questione. issue riaperta

**Comment by ale8530** [comment]
Thanks ingbrzy.

Issue closed

**Comment by fratoff91** [comment]
Quindi ora dovrebbe essere con le impostazioni della rom di xiaomi eu? Al prossimo update vi dirò se funziona. Grazie mille, intanto...😊
