### ISSUE TITLE
Problema di traduzione in Notifica (kenzo) - MIUI 6.10.13

### ISSUE THREAD

**Issue by filemone** [MishFdM/MIUI_V8_Italy#51]
![screenshot_2016-11-02-00-31-34-341_com miui home](https://cloud.githubusercontent.com/assets/23130299/19924176/1eda61e0-a0eb-11e6-9ce8-717dcdde13ac.png)

**Comment by ale8530** [comment]
Che versione rom monti?

Se gentilmente mi confermi questi bug sulla prossima release, kenzo è un pò indietro a causa di xiaomi

**Comment by filemone** [comment]
La rom "MIUI 8 by miui.it 6.10.13 Sviluppatore"

**Comment by ale8530** [comment]
@MishFdM  richiesto controllo stringhe apk "XiaomiSimActivateService.apk"

Bug traduzione fixato.
