### ISSUE TITLE
Traduzione mancante in Impostazioni -> Non disturbare (ido 6.11.3 by miui.it)

### ISSUE THREAD

**Issue by Caledor** [MishFdM/MIUI_V8_Italy#52]
Calls/messages from -> Chiamate/messaggi da

![screenshot_2016-11-07-09-25-16-146_com android settings](https://cloud.githubusercontent.com/assets/12029224/20050911/60c7f894-a4cc-11e6-99e4-f4a5f09dfd75.png)

**Comment by Caledor** [comment]
il bug persiste in 6.11.10 perchè la modifica è stata annullata con commit bf9458315303aa79e358d845eeac01544b02d335

**Comment by ale8530** [comment]
Faccio vedere a mish

**Comment by ale8530** [comment]
Hai ragione

**Comment by ale8530** [comment]
Sistemata https://github.com/MishFdM/MIUI_V8_Italy/commit/ac4c6ef5075eda82df97535603202cc10de2faa6

@MishFdM  è stato avvisato del fix :)

Ottimo lavoro @Caledor grazie per l'aiuto

**Comment by Caledor** [comment]
ritornato anche questo bug, fix annullato sempre con commit 22b92f583e2012f4472e6b67ea36799602b2c2d3

**Comment by ale8530** [comment]
Stessa motivazione https://github.com/MishFdM/MIUI_V8_Italy/issues/60#issuecomment-268109551
