### ISSUE TITLE
Traduzione mancante / Errore di traduzione in Impostazioni -> Schermata di sblocco e password (ido 6.11.3 by miui.it) 

### ISSUE THREAD

**Issue by Caledor** [MishFdM/MIUI_V8_Italy#56]
"Lockscreen" (sugg. "Schermata di sblocco") e "Password privacy".

Inoltre credo che come nome di default per le impronte sia meglio qualcosa come "Impronta1" anziché "Gestione impronte1" se possibile.

![screenshot_2016-11-07-02-17-00-928_com android settings](https://cloud.githubusercontent.com/assets/12029224/20051410/29dfd1b4-a4cf-11e6-9274-48a53b028d6a.png)

**Comment by ale8530** [comment]
Sistemata losckreen, e sistemato visualizzazione in "Gestione impronte 1", la traduzione Gestione impronte è corretta

**Comment by ale8530** [comment]
https://github.com/MishFdM/MIUI_V8_Italy/commit/39ad1c8c505242e36d7ca2b47359699df17e242e

Fissato qui
