### ISSUE TITLE
Errore di traduzione in Impostazioni -> Impostazioni aggiuntive -> Tasti (ido 6.11.3 by miui.it)

### ISSUE THREAD

**Issue by Caledor** [MishFdM/MIUI_V8_Italy#57]
Nel menu a tendina che appare selezionando uno tra Recenti, Home, Indietro sotto Pressione prolungata tasti, "Chiudi applicazioni recenti" è scorretto. Credo sia più corretto "Chiudi applicazione corrente".

![screenshot_2016-11-07-00-29-32-711_com android settings](https://cloud.githubusercontent.com/assets/12029224/20051501/a3943216-a4cf-11e6-99cd-70a429e64ab9.png)

**Comment by ale8530** [comment]
No questa va bene cosi.

Chiusa

**Comment by Caledor** [comment]
per curiosità, come mai? A titolo informativo, io mi sono limitato a constatare quello che faceva l'opzione (che effettivamente chiude solo l'app in primo piano, quindi già il plurale stona) senza andare a vedere la stringa in inglese. Inoltre se non sbaglio nella Miui 7 questa stringa era proprio riportata come "Chiudi applicazione corrente"

**Comment by ale8530** [comment]
La traduzione era corretta, ma dopo la tua verifica, ho provato personalmente è cosi, fix sistemato.

**Comment by Caledor** [comment]
Perfetto, ti ringrazio. Occhio però che adesso hai "Chiudi applicazionE recentI".

**Comment by Caledor** [comment]
Perfetto, ti ringrazio: occhio che però adesso hai "chiudi applicazionE recentI".
ne approfitto anche per dirti che ho commentato un paio di commit relativi ad altre issue... ti arrivano notifiche per quelli? perché in caso te li riporto come commenti nell'issue stessa (come qui) anziché direttamente al commit.
