### ISSUE TITLE
Bugs modifying a photo in Whatsapp

### ISSUE THREAD

**Issue by sharketor** [MishFdM/MIUI_V8_Italy#6]
Taking a photo in whatsapp chat --> modify --> cut --> words "Ok" and "Annulla" are white on white wallpaper.
![img_20160715_181154 1](https://cloud.githubusercontent.com/assets/20479619/16881325/fa3d35d8-4ab9-11e6-90e8-c1119c2f529c.jpg)

**Comment by MishFdM** [comment]
That's not our fault.
