### ISSUE TITLE
Traduzione mancante in Impostazioni -> Impostazioni aggiuntive -> Data e ora (ido 6.11.3 by miui.it) 

### ISSUE THREAD

**Issue by Caledor** [MishFdM/MIUI_V8_Italy#60]
"Choose date format" 2 volte (la seconda nel menu a tendina che appare selezionandola) e "Regional (xx/yy/zzzz) nel menu a tendina non sono tradotte.
![screenshot_2016-11-07-02-24-55-109_com android settings](https://cloud.githubusercontent.com/assets/12029224/20052083/8b40bb1e-a4d2-11e6-8562-9ebf624f11dd.png)
![screenshot_2016-11-07-02-24-59-618_com android settings](https://cloud.githubusercontent.com/assets/12029224/20052084/8bf82d4e-a4d2-11e6-802e-772bbc24982f.png)

**Comment by Caledor** [comment]
anche questo è stato annullato con commit bf9458315303aa79e358d845eeac01544b02d335

**Comment by ale8530** [comment]
Sistemato

@MishFdM

**Comment by Caledor** [comment]
il bug è tornato di nuovo nella 6.12.15. stavolta il commit "incriminato" è il 22b92f583e2012f4472e6b67ea36799602b2c2d3

**Comment by ale8530** [comment]
Ho applicato un fix al nostro tool di costruzione ora queste stringhe non saranno più perse, purtroppo le troppe versioni android ci creano grossi problemi :), ovviamente il fix sarà solo sulle rom miui.it

@MishFdM
