### ISSUE TITLE
Traduzione mancante in Spazio secondario (ido 6.11.10 by miui.it) 

### ISSUE THREAD

**Issue by Caledor** [MishFdM/MIUI_V8_Italy#63]
Il messaggio che appare quando si cerca di eliminare uno spazio secondario creato in precedenza non è stato tradotto

![screenshot_2016-11-10-23-09-02-104_com miui securitycore](https://cloud.githubusercontent.com/assets/12029224/20200374/2835805e-a7b1-11e6-975e-911580dce3df.png)

**Comment by ale8530** [comment]
Aggiornare ad una release più recente e confermare se c'è ancora lo stesso bug

**Comment by Caledor** [comment]
Confermato in 6.11.10. Ho notato anche che ci sono altre stringhe non tradotte relative allo spazio secondario

**Comment by ale8530** [comment]
Aggiungile qui con screenshot

**Comment by ale8530** [comment]
Prima di fare screenshot puoi cercarle nella nostra repo e se ci sono tradurle se vuoi

**Comment by Caledor** [comment]
avevo gia pensato di dedicarmi alle mie issue come ho fatto con l'altra ma volevo prima fare la pr di prova. puoi lasciare sia questa che l'altra come sono e me ne occuperò io a giorni

**Comment by ale8530** [comment]
ho fixato la issue ma ci sono ancora alcune stringhe da fare se vuoi apk di riferimento è questo-->https://github.com/MishFdM/MIUI_V8_Italy/blob/master/Italian/main/SecurityCoreAdd.apk/res/values-it/strings.xml

Ci fa piacere se ci dai una mano

**Comment by ale8530** [comment]
Scrivimi ad ale@miui.it , mi serve la tua email :)
