### ISSUE TITLE
Imperfezione traduzione

### ISSUE THREAD

**Issue by Stefano131270** [MishFdM/MIUI_V8_Italy#64]
Sicurezza
Batteria
Utilizzo batteria Hardware
Telefono inattivo

Doverebbe essere telefono in attivo oppure telefono attivo
Altrimenti sembra non utilizzato
Grazie mille
Ciao Stefano

**Comment by ale8530** [comment]
Senza screenshot non prendiamo in considerazione la tua segnalazione.

Se cortesemente puoi postarla e indicare versione miui installata

**Comment by Stefano131270** [comment]
Ok, dopo
grazie mille

_Google Mail_

2016-11-11 9:15 GMT+01:00 ale8530 notifications@github.com:

**Comment by ale8530** [comment]
Lo screenshot?

**Comment by ale8530** [comment]
Chiusa è altra issue
