### ISSUE TITLE
Creare uno spazio nella traduzione

### ISSUE THREAD

**Issue by Stefano131270** [MishFdM/MIUI_V8_Italy#65]
Sicurezza
Batteria
Utilizzo batteria Hardware
Telefono inattivo

ROM HMNote 2 xiaomi.eu

Doverebbe essere telefono in attivo oppure telefono attivo
Altrimenti sembra non utilizzato
Grazie mille
Ciao Stefano
![screenshot_2016-11-11-09-45-51-775_com miui securitycenter](https://cloud.githubusercontent.com/assets/16607220/20209602/79b27060-a7f5-11e6-8459-8c235316978a.png)

**Comment by ale8530** [comment]
Aggiornare ad una release più recente e confermare se c'è ancora lo stesso bug

**Comment by Caledor** [comment]
credo che questa fosse corretta com'era prima. Lo stato idle del telefono è la sospensione, insomma quando è bloccato e lo schermo è spento.

**Comment by Stefano131270** [comment]
Oggi presero' attenzione ancora.
se capisco bene secondo te e' ore di sdatndby - ore SOT?
ok questo e' quello che pensavo anche io, poi confrontando ad esempio 10
standy - 3 SOT, non avevo 7 ma ancora 10
Oggi controllo nuovamente, poi ti faccio sapere.
Bello comunicare cosi', grazie per la grande assistenza e per tutte le ore
che investi in questa passione.
A presto
Stefano

_Google Mail_

2016-11-16 0:22 GMT+01:00 Alessio Ceccarelli notifications@github.com:

**Comment by ale8530** [comment]
Abbiamo ripristinato la vecchia traduzione perché è quella più adatta alla funzione

**Comment by Stefano131270** [comment]
Ho verificato e ti stavo scrivendo proprio adesso, hai ragione
è lo standby meno il SOT
SCUSAMI TANTO

_Google Mail_

2016-11-16 9:38 GMT+01:00 ale8530 notifications@github.com:

**Comment by ale8530** [comment]
Non c'è bisogno di scusarsi 👍 ,grazie per la collaborazione

**Comment by Stefano131270** [comment]
Grazie ale 👍

_Google Mail_

2016-11-16 9:47 GMT+01:00 ale8530 notifications@github.com:
