### ISSUE TITLE
Traduzione errata in Musica->Playlist (ido 6.11.3 by miui.it) 

### ISSUE THREAD

**Issue by Caledor** [MishFdM/MIUI_V8_Italy#66]
Dovrebbe essere "Eliminare la playlist [...]"
![screenshot_2016-11-11-16-23-23-562_com miui player](https://cloud.githubusercontent.com/assets/12029224/20219796/47bd9d92-a82b-11e6-8343-7c39b23b328d.png)

**Comment by ale8530** [comment]
Closed
