### ISSUE TITLE
Errori di traduzione in Musica (ido 6.11.10 by miui.it) 

### ISSUE THREAD

**Issue by Caledor** [MishFdM/MIUI_V8_Italy#67]
"Il mio account" è errato, dovrebbe essere "Account Mi" o "Mi Account" a seconda di ciò che viene usato in altre app tipo Settings. In ogni caso il mio suggerimento è di passare tutto a "Account Mi" in quanto più "italiano" come costruzione rispetto al secondo.

La descrizione di Impostazioni avanzate contiene alcuni errori minori di traduzione e inconsistenze, come la minuscola iniziale e la cosiddetta "mod. Sleep" chiamata Timer ascolto nel menu.
**Sugg**: "Impostazioni download, timer ascolto, dati mobili, filtri per i file, ecc." 
![screenshot_2016-11-11-16-22-48-322_com miui player](https://cloud.githubusercontent.com/assets/12029224/20219856/7d49a794-a82b-11e6-8d8d-fb6bb1af94b6.png)
![screenshot_2016-11-11-16-28-42-454_com miui player](https://cloud.githubusercontent.com/assets/12029224/20220189/dad2eb0e-a82c-11e6-9c48-3ec787034be2.png)

**Comment by ale8530** [comment]
Aggiornare ad una release più recente e confermare se c'è ancora lo stesso bug

**Comment by Caledor** [comment]
Confermato in 6.11.10

**Comment by Caledor** [comment]
Ne approfitto per chiederti che ne pensi riguardo il passaggio da "Mi Account" a "Account Mi", come ti ho accennato nella descrizione. Se sei d'accordo ci metto 5 minuti a farlo e te lo mando con una PR

**Comment by ale8530** [comment]
Tutte le app o servizi di xiaomi devono iniziare con "Mi" davanti ad esempio:

Mi Account
Mi Cloud
ecc

**Comment by Caledor** [comment]
Lo so che è così, ma c'è una ragione particolare?

Perché quello che ho pensato io (e che probabilmente avrei dovuto motivarti meglio dall'inizio) è l'eccezione specifica per Mi Account perché questo non è il nome di un servizio come Mi Cloud ma un account (termine generico) di tipo "Mi".

Per fare qualche parallelismo con altri marchi, su google vedi "Accedi col tuo account Google per utilizzare Google Drive" o "Accedi con l'ID Apple per entrare nell'Apple Store", mentre "Google account" e "apple id" appartengono all'inglese.

Spero di essere stato chiaro perché mi rendo conto che possa sembrare incasinata la questione.

**Comment by ale8530** [comment]
Direttive di Xiaomi sulla Global  :)

**Comment by Caledor** [comment]
Ahah perfetto allora come non detto
