### ISSUE TITLE
Traduzione mancante in Updater -> Riepilogo aggiornamento (ido 6.11.17)

### ISSUE THREAD

**Issue by Caledor** [MishFdM/MIUI_V8_Italy#75]
![screenshot_2016-11-15-00-01-13-723_com android updater](https://cloud.githubusercontent.com/assets/12029224/20583567/8f9f9ef2-b1eb-11e6-8685-58f24bcebf75.png)

**Comment by ale8530** [comment]
Server xiaomi non si può tradurre
