### ISSUE TITLE
Traduzione mancante in Impostazioni -> Mi account -> Mi Cloud -> Archiviazione (ido 6.11.17)

### ISSUE THREAD

**Issue by Caledor** [MishFdM/MIUI_V8_Italy#76]
![screenshot_2016-11-21-19-38-12-325_com miui cloudservice](https://cloud.githubusercontent.com/assets/12029224/20583633/f9f4fa40-b1eb-11e6-8fd2-da6cdcc11fd6.png)

**Comment by ale8530** [comment]
Da server xiaomi non può essere tradotta
