### ISSUE TITLE
Traduzioni mancanti in Temi (?) (ido 6.11.17)

### ISSUE THREAD

**Issue by Caledor** [MishFdM/MIUI_V8_Italy#77]
Non sono sicuro che gli elementi negli screen siano traducibili, per questo ho messo il (?).

![screenshot_2016-11-17-23-18-34-930_com android thememanager](https://cloud.githubusercontent.com/assets/12029224/20595348/e95edfc2-b239-11e6-9bc2-ea29bd88b039.png)
![screenshot_2016-11-24-11-37-15-986_com android thememanager](https://cloud.githubusercontent.com/assets/12029224/20595532/868dffee-b23a-11e6-9d7e-908339211922.png)
![screenshot_2016-11-24-11-35-59-172_com android thememanager](https://cloud.githubusercontent.com/assets/12029224/20595533/88a83a74-b23a-11e6-9fdf-2872139444a2.png)

**Comment by ale8530** [comment]
Tutto normale queste non posso essere cambiate
