### ISSUE TITLE
Percentuale batteria updater

### ISSUE THREAD

**Issue by patit72** [MishFdM/MIUI_V8_Italy#8]
Probabilmente c'è un errore nella percentuale che deve essere rilevata (vedi screenshot)

![screenshot_2016-07-22-11-36-42-644_com android updater](https://cloud.githubusercontent.com/assets/16647912/17053762/cc5fbcc2-5003-11e6-954f-110af3e56525.png)

**Comment by ingbrzy** [comment]
https://github.com/Acid-miuipolskapl/v8-XML-Compare/blob/master/gemini/Updater.apk/res/values/strings.xml#L160
