### ISSUE TITLE
Errore di battitura REDMI 4 pro 6.12.1 miui.it

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V8_Italy#80]
REDMI 4 pro versione 6.12.1 bt Miui.it, mettendo il telefono in landscape e bloccando la rotazione, appare il toast con scritto "Autorazione disattivata", propongo di correggerlo con "Autorotazione disattivata" o " Rotazione disattivata", grazie![screenshot_2016-12-07-18-46-54-688_com android settings](https://cloud.githubusercontent.com/assets/22968844/21035360/b3e4a1d4-bdbe-11e6-8b43-3bdb09f05545.png)

**Comment by MishFdM** [comment]
Corretto, grazie per la segnalazione.
