### ISSUE TITLE
"Tasti" in Impostazioni aggiuntive non funziona (Kate) 

### ISSUE THREAD

**Issue by Federic095** [MishFdM/MIUI_V8_Italy#83]
Quando cerco di entrare in "Tasti" l'app Impostazioni crasha. Devo mettere lingua inglese per poter utilizzare quell'impostazione.

**Comment by ale8530** [comment]
Che rom monti? Screenshot errore grazie

**Comment by Federic095** [comment]
Ciao Ale, grazie per la risposta 
![screenshot_2016-12-22-07-05-38-448_com android settings](https://cloud.githubusercontent.com/assets/22075569/21416698/3503328e-c815-11e6-9661-b2ccebf6fb06.png)

![screenshot_2016-12-22-07-05-52-756_com android settings](https://cloud.githubusercontent.com/assets/22075569/21416702/3bf2ad90-c815-11e6-8b91-a49eb26f8a23.png)

**Comment by ale8530** [comment]
La nostra traduzione non ha bug,parlerò con ingbrzy

Translation:
Our translation has no bugs, I will speak with @ingbrzy

**Comment by ingbrzy** [comment]
fixed by https://github.com/MishFdM/MIUI_V8_Italy/commit/b4dece73c751bd9fdb82800cdbb77eefde7b5e2e#diff-1e70e4074af97d40fbf4b30810ac3be1L631

**Comment by ale8530** [comment]
Ok nel prossimo aggiornamento

I spoke with @ingbrzy should not have the problem the next update
