### ISSUE TITLE
Mancata traduzione in Hotspot Personale (Kate) 

### ISSUE THREAD

**Issue by Federic095** [MishFdM/MIUI_V8_Italy#84]
Andando in "Dispositivi collegati" nella sezione Hotspot Personale, manca la traduzione (Kate) 

![screenshot_2016-12-22-06-48-15-297_com android settings](https://cloud.githubusercontent.com/assets/22075569/21416383/bbd014a6-c812-11e6-8e8c-c17ef6958082.png)

**Comment by ale8530** [comment]
Che rom monti?

**Comment by Federic095** [comment]
![screenshot_2016-12-22-07-08-38-731_com android settings](https://cloud.githubusercontent.com/assets/22075569/21416733/87730724-c815-11e6-9356-2ac12ddec15c.png)

**Comment by ale8530** [comment]
Qui appena possibile verifico le stringhe

**Comment by Federic095** [comment]
Perfetto, grazie :)
