### ISSUE TITLE
2 errori in menu ita miui8

### ISSUE THREAD

**Issue by andrealenzi** [MishFdM/MIUI_V8_Italy#85]
Per contribuire all'ottimo lavoro fatto dal team miui.it e rendere la traduzione buona quanto la parte software, ecco il mio contributo (frutto di studi classici e passione per la filologia).

Buon lavoro!

1.
nell'app telefono/recenti/impostazioni/chiamate/impostazioni avanzate/promemoria chiamate perse,
c'è scritto "riguardo le chiamate", ma 
l'unica forma possibile in italiano è "riguardo ALLE chiamate" 

2.
"SCANDIRE" va messo al posto di "scansionare" poiché è l'unica forma corretta; vedi dizionario, o leggi qui di seguito.

Perché "scansionare", "scansire", "scannare" e "scannerizzare" sono errori? 

A. 
NON SONO NEOLOGISMI:
il neologismo nasce per descrivere qualche cosa di nuovo, cioè non descrivibile con le parole già disponibili, mentre nel nostro caso non c'è bisogno di 
neologismi poiché il verbo già esiste ed è "SCANDIRE".

in ogni caso, se mancasse il verbo adatto, il neologismo corretto sarebbe il solo "scannerizzare", poiché in italiano i verbi da parole straniere si 
ottengono aggiungendo il suffisso -izzare ai sostantivi stranieri; 

quindi, usare "scannerizzare" al posto di "scandire", sarebbe come usare "walkerizzare" al posto di "camminare".

B.
di norma, da un punto di vista etimologico, i verbi danno origine ai sostantivi; non il contrario.
è per questo meccanismo che il verbo "scandire" ha dato origine al sostantivo "scansione", così come da "estendere" deriva "estensione".

qualche "pigro" nel consultare il dizionario, però, ha deciso di creare il verbo a partire dal sostantivo "scansione", in un fiorire di "scansionare", "scansire", "scannare", che giornalisti altrettanto "pigri" utilizzano, senza prendersi la briga di sfogliare un dizionario;

come se dal sostantivo "estensione" si inventasse il verbo "estensionare", o "estensire", ignorando il verbo "estendere".

L'unico verbo giusto è "SCANDIRE": 
dal verbo latino "scando" (scandi, scansum, scandere, con radice "scan", usato in metrica per indicare la scomposizione/ricomposizione elemento per elemento 
della parola/verso) è nato il verbo italiano "scandire" con identico significato meetrico, fino a che, negli agli anni '40 fu usato per descrivere la formazione delle immagini sul tubo catodico dei televisori, inventati proprio in quegli anni.

Identico ragionamento fecero gli inglesi che presero il verbo latino "scando" e crearono il loro verbo "to scan", dal quale poi derivò la parola "scanner" 

che è appunto l'apparecchio che scandisce le immagini, cioè digitalizza immagini analogiche (scanner è sia participio presente del verbo "to scan", sia sostantivo).

"scansionare", "scansire", "scannare" e "scannerizzare" sono quindi banali errori dovuti all'ignoranza del vocabolo corretto, diventati poi di uso comune in quanto usati in articoli e servizi in tv, che appaiono come fonti autorevoli ai lettori, i quali poi si abituano ad usarli in un circolo vizioso, rendendo desueto e quindi "strano da dire" l'unico verbo corretto.

Risposte alle obiezioni più frequenti di chi a tutti i costi vuole usare "scansionare", "scansire", "scannare" e "scannerizzare": 

-è "evoluzione" della lingua:
NO, è ignoranza, 
visto che esiste un dizionario e passiamo centinaia di ore a scuola a studiare italiano, segno che l'intenzione è quella di tramandare, non di innovare secondo gli usi della maggioranza della popolazione (che è solitamente la meno acculturata).
Se, però, si ritiene che l'apprendimento della lingua debba essere "dinamico" ed "improntato all'evoluzione", allora potremmo eliminare i dizionari e le migliaia di ore di italiano che si studiano a scuola dalle elementari alle scuole superiori, risparmiando soldi e tempo e lasciando TV e lingua parlata come maestre che sono quasi gratuite;
basta mettersi d'accordo

-è "strano da dire":
NO.
ci si abitua dopo poco; anzi sembrerà strano il contrario dopo appena una paio di volte.

-scandire ha un solo significato ed è quello metrico:
NO.
capita spesso in italiano e nelle altre lingue che un vovabolo sia usato con diversi significati:
ad es. il verbo "tradurre" lo troviamo sia nell'accezione di "traduzione da una lingua all'altra", sia in quella di "traduzione in carcere dei condannati"

**Comment by MishFdM** [comment]
1. Corretto
2. In fase di valutazione. http://www.accademiadellacrusca.it/it/lingua-italiana/consulenza-linguistica/domande-risposte/scannare-scannerizzare-scansionare
