### ISSUE TITLE
Piccole imprecisioni - Redmi 4 Prime 6.12.22 xiaomi.eu

### ISSUE THREAD

**Issue by darioct46** [MishFdM/MIUI_V8_Italy#86]
1 - Dopo aver fatto "Invia" per condividere un file, appare un popup nella parte inferiore che non riesco a shottare perché scompare all'istante. Dovrebbe essere "Lapplicazione si sta avviando". Manca l'apostrofo.

2 - Impostazioni - Notifiche - Stile barra di stato. Si potrebbe optare per Combinato e Separato

![screenshot_2016-12-24-22-35-43-043_com android settings](https://cloud.githubusercontent.com/assets/24757829/21468841/985b6998-ca2a-11e6-8556-ce1bbf7083ca.png)

3 - Impostazioni - Impostazioni aggiuntive - Opzioni sviluppatore

- Nell'ultima voce Attiva "debugg" ANR da correggere con "debug"

![screenshot_2016-12-24-22-58-21-501_com android settings](https://cloud.githubusercontent.com/assets/24757829/21468885/e8632136-ca2c-11e6-8bc4-4316c2ebdcf2.png)

- Aggressivo handover... -> Propongo qualcosa come "Forza utilizzo del Wi-Fi sulla rete cellulare"
- Wi-Fi Roam Scans -> scansione reti Wi-Fi?
- Use legacy DHCP client -> Usa client DHCP legacy
Usa il client DHCP di Lollipop al posto del nuovo client DHCP Android

![screenshot_2016-12-24-22-50-23-702_com android settings](https://cloud.githubusercontent.com/assets/24757829/21468903/e3e4e0bc-ca2d-11e6-9e28-26f73912b814.png)

**Comment by ale8530** [comment]
1 - issue non trovata
2 - issue sistemata
3 - non accettata
