### ISSUE TITLE
Crash Impostazioni in Non disturbare 

### ISSUE THREAD

**Issue by Federic095** [MishFdM/MIUI_V8_Italy#87]
Buon natale a tutti! 

Andando a creare una lista personalizzata di contatti, nella sezione Non disturbare, una volta che li seleziono manualmente e premo "ok", l'app Impostazioni crasha e i contatti selezionati non rimangono salvati. Redmi Note 3 Internazionale (Kate) 
![screenshot_2016-12-25-09-11-53-962_com android settings](https://cloud.githubusercontent.com/assets/22075569/21470300/cd3147e8-ca82-11e6-9de1-6fc9f3d1321c.png)
![screenshot_2016-12-25-09-11-26-144_com android settings](https://cloud.githubusercontent.com/assets/22075569/21470302/ddf66734-ca82-11e6-8ada-8485653a5e2c.png)
![screenshot_2016-12-25-09-12-22-518_com android settings](https://cloud.githubusercontent.com/assets/22075569/21470303/e7878328-ca82-11e6-983e-d70ac2fd3302.png)

**Comment by ale8530** [comment]
Aggiorna a versione più recente xiaomi.eu

**Comment by Federic095** [comment]
Fatto, ancora non funziona

**Comment by Federic095** [comment]
![screenshot_2016-12-25-09-42-03-339_com android settings](https://cloud.githubusercontent.com/assets/22075569/21470382/6b2ee1e6-ca86-11e6-9b6c-2ddbb25565d7.png)

**Comment by ale8530** [comment]
Non è un bug di traduzione, ho provato la mia rom e non ci sono bug. Mi spiace.

Comunque mi sembra strano non puoi avere problemi.

Prova a mettere in inglese e vedi che ti fa.

**Comment by Federic095** [comment]
Crasha pure in inglese 😂 Però è strano, ho fatto pure un Wipe data qualche giorno fa...

**Comment by ale8530** [comment]
È un bug della rom allora non dipende da noi
