### ISSUE TITLE
Mancanza traduzioni in MiRemote 

### ISSUE THREAD

**Issue by Federic095** [MishFdM/MIUI_V8_Italy#88]
Buongiorno, con il Kate ho notato che mancano traduzioni nell'app MiRemote 
![screenshot_2016-12-30-11-11-18-824_com android settings](https://cloud.githubusercontent.com/assets/22075569/21563421/abd7e5a8-ce82-11e6-8313-d2fe3555b77d.png)
![picsart_12-30-11 04 47](https://cloud.githubusercontent.com/assets/22075569/21563424/b2127f32-ce82-11e6-8b82-34eb9fa07bf5.jpg)

**Comment by Federic095** [comment]
![picsart_12-30-11 04 15](https://cloud.githubusercontent.com/assets/22075569/21563452/f239185a-ce82-11e6-8433-f25cbe13f241.jpg)

**Comment by ale8530** [comment]
WIP

**Comment by Federic095** [comment]
Ale, ho notato altre traduzioni mancanti. Una volta creata la configurazione per un dispositivo, con il telecomando davanti (come nel secondo screen che avevo postato), se premo i tre pallini in alto a destra per andare nelle impostazioni, i mancano delle traduzioni. Posto lo screen

![screenshot_2017-01-11-20-13-41-172_com duokan phone remotecontroller](https://cloud.githubusercontent.com/assets/22075569/21862659/7c06ec54-d83a-11e6-95cc-92662e0acbc8.png)

**Comment by ale8530** [comment]
Aspettare prossima release grazie
