### ISSUE TITLE
Crash quando blocco un numero 

### ISSUE THREAD

**Issue by Federic095** [MishFdM/MIUI_V8_Italy#89]
Kate con ultima dev,  quando tento di bloccare un numero, crashano le impostazioni 
![screenshot_2016-12-30-12-43-08-704_com android mms](https://cloud.githubusercontent.com/assets/22075569/21564448/f50411ec-ce8d-11e6-8d68-fc18edb40c9d.png)
https://cloud.githubusercontent.com/assets/22075569/21563421/abd7e5a8-ce82-11e6-8313-d2fe3555b77d.png

**Comment by ale8530** [comment]
Non è nostro bug
