### ISSUE TITLE
Clona app - Secondo Spazio - Impostazioni telefono

### ISSUE THREAD

**Issue by birimbo79** [MishFdM/MIUI_V8_Italy#9]
Le app Clona app e Secondo spazio non sono tradotte:
![screenshot_2016-07-22-18-51-43-647_com miui securitycore](https://cloud.githubusercontent.com/assets/20362846/17064706/36d5339a-503e-11e6-8216-618d09d30b74.png)
![screenshot_2016-07-22-18-52-07-341_com miui securitycore](https://cloud.githubusercontent.com/assets/20362846/17064884/2320cade-503f-11e6-9c67-e47c2b775c2c.png)
Sarebbe possibile tradurle?

Nelle impostazioni delle chiamate nella voce "Blacklist" è presente "Registrazione automatica attivata" ma non si tratta del registratore e sarebbe più corretto "Filtro chiamate attivato" o "Filtro chiamate disattivo"
![screenshot_2016-07-22-18-18-13-763_com android phone](https://cloud.githubusercontent.com/assets/20362846/17064792/a16b1896-503e-11e6-860c-ea5d9592ce70.png)

**Comment by ale8530** [comment]
La sezione clona app è in fase di traduzione e sarà sistemata nelle prossime release, il problema di registrazione automatica attivata va bene cosi è tradotta correttamente.
