### ISSUE TITLE
[ROLEX] Permessi

### ISSUE THREAD

**Issue by croccio** [MishFdM/MIUI_V8_Italy#90]
Quando viene chiesto di accettare o rifiutare dei permessi le scritte sono in inglese.

**Comment by ale8530** [comment]
Screenshot grazie

**Comment by croccio** [comment]
![img-20161230-wa0000](https://cloud.githubusercontent.com/assets/3746525/21573059/96144fc8-cee0-11e6-8b2f-23336b2054ba.jpg)




Il 30/dic/2016 14:26, "ale8530" <notifications@github.com> ha scritto:

**Comment by croccio** [comment]
ho guardato i commit e mi sembra di nonuser trovato nessun riferimento a questa cosa: oltre al consenti e nega come pulsanti nel dialog, ci sarebbe l'"Allow" iniziale nella frase prima del nome dell'app. Non so se quella correzione implica la modifica anche nella frase.

**Comment by ale8530** [comment]
Se è stato fissato fidati,non mi sembra opportuno questo tuo mex devi vedere packageinstaller.apk
