### ISSUE TITLE
Traduzioni in Calendario 

### ISSUE THREAD

**Issue by Federic095** [MishFdM/MIUI_V8_Italy#91]
Buonasera, ho trovato delle traduzioni mancanti nell'app Calendario. Redmi Note 3 Internazionale (Kate) 
![screenshot_2017-01-13-17-08-19-469_com android settings](https://cloud.githubusercontent.com/assets/22075569/21938279/f20dfede-d9ba-11e6-9122-c6ba89345132.png)
![screenshot_2017-01-13-17-07-46-925_com android calendar](https://cloud.githubusercontent.com/assets/22075569/21938292/fbb88288-d9ba-11e6-83db-56a635dc729f.png)
![screenshot_2017-01-13-17-08-09-605_com android calendar](https://cloud.githubusercontent.com/assets/22075569/21938298/054b1c34-d9bb-11e6-9b42-335fa0be7b86.png)
![screenshot_2017-01-13-17-08-03-389_com android calendar](https://cloud.githubusercontent.com/assets/22075569/21938307/0cb700aa-d9bb-11e6-857e-796a4849b2db.png)

**Comment by ale8530** [comment]
Da me sono tradotte

**Comment by Federic095** [comment]
Sulla 1.19 sono ancora in inglese... Bisogna avvertire sul forum della Eu?

**Comment by ale8530** [comment]
Devi aspettare prossima release, le loro traduzioni sono sempre più indietro,comunque ho chiesto un controllo a chi ha 6.0, perchè ho notato che due stringhe io non c'è l'ho, con tutte queste versioni android è diventato un macello

**Comment by Federic095** [comment]
Perfetto, ti ringrazio. Aspetterò allora

**Comment by ale8530** [comment]
Confermato sono da tradurre.

@MishFdM
