### ISSUE TITLE
crash browser

### ISSUE THREAD

**Issue by bugrider87** [MishFdM/MIUI_V8_Italy#93]
Terminale redmi note 3 speciale edition
ROM miui it 7.1.19

L'approvazione browser si e bloccata in modo anomalo. Il bug si verifica su lingua italiana ed inglese altre lingue non ho provato... Al momento non riesco a caricare screanshot

**Comment by ale8530** [comment]
Farò un controllo sulla rom e ti contatto sul forum :)

**Comment by ale8530** [comment]
Flasha questa rom fix-->https://drive.google.com/drive/my-drive

Fammi sapere

**Comment by bugrider87** [comment]
purtroppo cliccando sul link mi porta sul mio google drive e ai miei file personali dovresti accedere al tuo drive click desto sul file da condividere=>ottieni linck condivisibile e postare tale linck dando i premessi di visualizzazione nel caso siano disattivi

**Comment by ale8530** [comment]
Riprova qui https://drive.google.com/file/d/0B7Jt4O5aMbsVc2F1aG1iMjNPMTQ/view?usp=drivesdk

Non c'è nessun blocco

**Comment by bugrider87** [comment]
perfetto il browser funziona alla perfezione
