### ISSUE TITLE
problemi riscontrati miui it 7.1.19 su redmi note 3 kate

### ISSUE THREAD

**Issue by bugrider87** [MishFdM/MIUI_V8_Italy#94]
1: tempi di ricarica un po troppo lunghi: ci vogliono 5 ore per ricaricare una batteria che si trova al 45%

2: eccessivo consumo di batteria cio non toglie che si arrivi a fine giornata con circa il 30-45% di carica residua con 3 ore circa di schermo attivo e uso moderato/ limitato di app come facebook whatsapp ecc

3: nel menu impostazioni=>schermata di blocco e password "gestisci importe" gestisci non e corretto sarebbe più corretto "gestione"

4: nel menu impostazioni=>schermata di blocco e password=>gestisci importe=>aggiungi impronta digitale manca 'l' animazione e le indizazioni, ciò non toglie che il fingerprint funzioni alla perfezione

**Comment by ale8530** [comment]
Questi non sono bug da postare qui e non riguardano noi, è stata fatta un eccezione solo sulla rom, ma generalmente solo traduzione
