### ISSUE TITLE
Sottomenú consumo batteria

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V8_Italy#95]
Il sottomenú "consumo batteria" nel menú "batteria" delle impostazioni, crasha se si tenta di accedere ad esso senza l'ottimizzazione MIUI attivata dalle impostazioni sviluppatore.

<img src="http://oi65.tinypic.com/29cuq90.jpg">
<img src="http://oi63.tinypic.com/2wp59nd.jpg">

**Comment by Orlaff** [comment]
http://oi65.tinypic.com/29cuq90.jpg
http://oi63.tinypic.com/2wp59nd.jpg

**Comment by ghost** [comment]
Riscontrabile su Xiaomi.eu e Xiaomi.it 7.2.9, e Xiaomi.eu 7.2.16.

**Comment by ale8530** [comment]
Bug sistemato

@ingbrzy FC resolve
