### ISSUE TITLE
Galleria foto recenti

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V8_Italy#96]
Non tradotto...

<img src="http://oi64.tinypic.com/290szh4.jpg">
<img src="http://oi65.tinypic.com/2eq9hsx.jpg">

**Comment by ghost** [comment]
Riscontrabile su Xiaomi.eu e Xiaomi.it 7.2.9, e Xiaomi.eu 7.2.16.

**Comment by ale8530** [comment]
Found new photos non esiste stringa al momento
