### ISSUE TITLE
Alcune voci nelle impostazioni non tradotte

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V8_Italy#98]
<img src="http://oi66.tinypic.com/244w80m.jpg">

**Comment by ghost** [comment]
Riscontrabile su Xiaomi.eu e Xiaomi.it 7.2.9, e Xiaomi.eu 7.2.16.

**Comment by ale8530** [comment]
Email Setting non è traducibile ancora, non esiste stringa
